apiVersion: v1
kind: Service
metadata:  
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-demo
  sessionAffinity: None
  type: ClusterIP

